apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-openmon
  namespace: kube-system
  labels:
    name: kube-openmon
    app: kube-openmon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-openmon
  template:
    metadata:
      labels:
        name: kube-openmon
        namespace: kube-system
    spec:
      containers:
        - name: kube-openmon
          image: michelgokan/kube-openmon
          env:
           - name: MONITORING_INTERVAL
             value: "1"
           - name: LOG_LEVEL
             value: "1"
           - name: ENABLED
             value: "1"
#           - name: KUBERNETES_CUSTOM_ADDRESS
#             value: ""
#           - name: KUBERNETES_CUSTOM_PORT
#             value: ""
           - name: INFLUXDB_ADDRESS
             value: "influx-influxdb.kube-system"
           - name: INFLUXDB_PORT
             value: "8086"
           - name: INFLUXDB_USERNAME
             value: ""
           - name: INFLUXDB_PASSWORD
             value: ""
           - name: INFLUXDB_DATABASE
             value: "kubernetes_michel"
           - name: KUBERNETES_CUSTOM_TOKEN
             value: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im15YWRtaW4tdG9rZW4td3RrN2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibXlhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijc1MDhlOGM4LTliYzMtMTFlOC05OTIzLTA4MDAyNzk5YTVmZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0Om15YWRtaW4ifQ.aQGWYNQ_HwjrKsM5r98uEl7XhfdYP7GX96kpN7p0emlIeVLT4bEpKUI_MafvBHflMmSJQPTXZ0tdDe6wLjuXTQ3gE-SoVlqmztdpywJ6V_H6s9Eugl6rEzIHwUw04J3TZSk4kRskb17P3ljIAqPxa1gu5TIif0b0tdEmliqs1-JpJcTZ2GQCKLLsg6axxnUDncho1g4dqRxZ7au1IljkbdowBtuv5EE3OFuwbk8-6-m_TDAx2fIH11mFCg5KSDWUKBmcak6Lp23PDL4LUWxvpsJjAuoZNdkVhJcrsVXMjneIWNW4Z3QlxrRPXYAnKzAMu-tpJfJV2sDRUJmE489ngw"
