apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-openmon
  namespace: kube-system
  labels:
    name: kube-openmon
    app: kube-openmon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-openmon
  template:
    metadata:
      labels:
        name: kube-openmon
        namespace: kube-system
    spec:
      containers:
        - name: kube-openmon
          image: michelgokan/kube-openmon
          env:
           - name: MONITORING_INTERVAL
             value: "{MONITORING_INTERVAL}"
           - name: LOG_LEVEL
             value: "{LOG_LEVEL}"
           - name: ENABLED
             value: "{ENABLED}"
#           - name: KUBERNETES_CUSTOM_ADDRESS
#             value: "{KUBERNETES_CUSTOM_ADDRESS}"
#           - name: KUBERNETES_CUSTOM_PORT
#             value: "{KUBERNETES_CUSTOM_PORT}"
#           - name: INFLUXDB_ADDRESS
#             value: "influxdb-influxdb.kube-system"
#           - name: INFLUXDB_PORT
#             value: "8086"
           - name: INFLUXDB_ADDRESS
             value: "{INFLUXDB_ADDRESS}"
           - name: INFLUXDB_PORT
             value: "{INFLUXDB_PORT}"
           - name: INFLUXDB_USERNAME
             value: "{INFLUXDB_USERNAME}"
           - name: INFLUXDB_PASSWORD
             value: "{INFLUXDB_PASSWORD}"
           - name: INFLUXDB_DATABASE
             value: "{INFLUXDB_DATABASE}"
           - name: KUBERNETES_CUSTOM_TOKEN
             value: "{KUBERNETES_CUSTOM_TOKEN}"
