apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-openmon
  namespace: kube-system
  labels:
    name: kube-openmon
    app: kube-openmon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-openmon
  template:
    metadata:
      labels:
        name: kube-openmon
        namespace: kube-system
    spec:
      containers:
        - name: kube-openmon
          image: michelgokan/kube-openmon
          env:
           - name: MONITORING_INTERVAL
             value: "1"
           - name: LOG_LEVEL
             value: "1"
           - name: ENABLED
             value: "1"
#           - name: KUBERNETES_CUSTOM_ADDRESS
#             value: ""
#           - name: KUBERNETES_CUSTOM_PORT
#             value: ""
           - name: INFLUXDB_ADDRESS
             value: "172.16.16.242"
           - name: INFLUXDB_PORT
             value: "8086"
           - name: INFLUXDB_USERNAME
             value: ""
           - name: INFLUXDB_PASSWORD
             value: ""
           - name: INFLUXDB_DATABASE
             value: "kubernetes_michel"
           - name: KUBERNETES_CUSTOM_TOKEN
             value: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImthdWFkbWluLXRva2VuLW1zZ2Y3Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImthdWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzg0ZTM5MDktN2Y5NC0xMWU4LWE0Y2ItZmExNjNlNmI2NTk3Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6a2F1YWRtaW4ifQ.MixqWWVr2C4qy_44hIr1bZo5dkSqqppKEFyY2rMxi7a2xFUr_MsNkp5gB81drbtSiFUEeN51pG25E5HGeoHHwbE-dpjR17Mp4TvTwaPLT63sRruzBy7uxeD1JaEw6gedKASBrOVDt3vu-7X7NKYac3aFk39kuoK5IlJN0oX4AstDJHSCx1yYwfeSW6sY9AnJvGXdFJ-vnA2ToQnrEz-Ytv_yNBo0pdb2zzIBE6KMecGWlQqEm2n6BIiSaDtAXNZKHgPFepOJA-5aGLsyqNW4R_JnaOlFhSVp4LvsTJI_JjVIVQIfMcR81JLGdkxNtessPH8JVfU9Ocy_Y3GMEyu7Lw"
